### ISSUE TITLE
Pusher_2d.xml does not exist

### ISSUE THREAD

**Issue by Skylark0924** [JannerM/mbpo#33]
Hi there, I'm trying to use Pusher2d-ImageReach-v0 env by creating a `pusher2d/0.py` config.

```
params = {
    'type': 'MBPO',
    'universe': 'gym',
    'domain': 'Pusher2d',
    'task': 'ImageReach-v0',

    'log_dir': '~/ray_mbpo/',
    'exp_name': 'defaults',

    'kwargs': {
        'epoch_length': 1000,
        'train_every_n_steps': 1,
        'n_train_repeat': 20,
        'eval_render_mode': None,
        'eval_n_episodes': 1,
        'eval_deterministic': True,

        'discount': 0.99,
        'tau': 5e-3,
        'reward_scale': 1.0,

        'model_train_freq': 1000,
        'model_retain_epochs': 5,
        'rollout_batch_size': 100e3,
        'deterministic': False,
        'num_networks': 7,
        'num_elites': 5,
        'real_ratio': 0.05,
        'target_entropy': -2,
        'max_model_t': None,
        'rollout_schedule': [20, 300, 1, 20],
        'hidden_dim': 400,
    }
}

```

However, I got this error:
```
Traceback (most recent call last):
  File "/home/lab/anaconda3/envs/mbpo/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 389, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/home/lab/anaconda3/envs/mbpo/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 252, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/lab/anaconda3/envs/mbpo/lib/python3.6/site-packages/ray/worker.py", line 2288, in get
    raise value
ray.exceptions.RayTaskError: ray_ExperimentRunner:train() (pid=8159, host=lab-server)
  File "/home/lab/anaconda3/envs/mbpo/lib/python3.6/site-packages/ray/tune/trainable.py", line 150, in train
    result = self._train()
  File "/home/lab/Github/TendonTrack/ipk_mbpo/examples/development/main.py", line 98, in _train
    self._build()
  File "/home/lab/Github/TendonTrack/ipk_mbpo/examples/development/main.py", line 48, in _build
    get_environment_from_params(environment_params['training']))
  File "/home/lab/Github/TendonTrack/ipk_mbpo/softlearning/environments/utils.py", line 34, in get_environment_from_params
    return get_environment(universe, domain, task, environment_kwargs)
  File "/home/lab/Github/TendonTrack/ipk_mbpo/softlearning/environments/utils.py", line 24, in get_environment
    env = ADAPTERS[universe](domain, task, **environment_params)
  File "/home/lab/Github/TendonTrack/ipk_mbpo/softlearning/environments/adapters/gym_adapter.py", line 68, in __init__
    env = gym.envs.make(env_id, **kwargs)
  File "/home/lab/anaconda3/envs/mbpo/lib/python3.6/site-packages/gym/envs/registration.py", line 156, in make
    return registry.make(id, **kwargs)
  File "/home/lab/anaconda3/envs/mbpo/lib/python3.6/site-packages/gym/envs/registration.py", line 101, in make
    env = spec.make(**kwargs)
  File "/home/lab/anaconda3/envs/mbpo/lib/python3.6/site-packages/gym/envs/registration.py", line 73, in make
    env = cls(**_kwargs)
  File "/home/lab/Github/TendonTrack/ipk_mbpo/softlearning/environments/gym/mujoco/image_pusher_2d.py", line 57, in __init__
    super(ImageForkReacher2dEnv, self).__init__(*args, **kwargs)
  File "/home/lab/Github/TendonTrack/ipk_mbpo/softlearning/environments/gym/mujoco/image_pusher_2d.py", line 11, in __init__
    Pusher2dEnv.__init__(self, *args, **kwargs)
  File "/home/lab/Github/TendonTrack/ipk_mbpo/softlearning/environments/gym/mujoco/pusher_2d.py", line 58, in __init__
    MujocoEnv.__init__(self, model_path=self.MODEL_PATH, frame_skip=5)
  File "/home/lab/anaconda3/envs/mbpo/lib/python3.6/site-packages/gym/envs/mujoco/mujoco_env.py", line 45, in __init__
    raise IOError("File %s does not exist" % fullpath)
OSError: File /home/lab/Github/TendonTrack/ipk_mbpo/models/pusher_2d.xml does not exist

```

Is there actually no model about it in your repository? 

Furthermore, the reason why I want to test this environment is trying to figure out the preprocessing method of image observation. Do you have any suggestions about that?

**Comment by Skylark0924** [comment]
After downloading the `pusher_2d.xml` from https://github.com/rail-berkeley/softlearning/blob/master/models/pusher_2d.xml, the issue solved.

**Comment by jannerm** [comment]
Is this issue resolved?

Since Pusher2d-ImageReach is not a standard gym environment, I think the solution you found (copying the xml manually to `models/`) is the right one.

**Comment by Skylark0924** [comment]
Yeah, it's solved.
