### ISSUE TITLE
'GymAdapter' object has no attribute '_Serializable__initialize'

### ISSUE THREAD

**Issue by Ramelol** [JannerM/mbpo#35]
Hi,

When I try to run the main example using `mbpo run_local examples.development --config=examples.config.halfcheetah.0 --gpus=1 --trial-gpus=1`, I have an issue with the classes that inherit from Serializable (GymAdapter, SoftlearningEnv, ImagePusher2dEnv...). The problem is that the `_Serializable__initialize` method is not defined:

```
2021-05-03 18:03:36,442	ERROR trial_runner.py:426 -- Error processing event.
Traceback (most recent call last):
  File "/home/ricardo/Documentos/venv_mbpo/env-py3.6/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 389, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/home/ricardo/Documentos/venv_mbpo/env-py3.6/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 252, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/ricardo/Documentos/venv_mbpo/env-py3.6/lib/python3.6/site-packages/ray/worker.py", line 2288, in get
    raise value
ray.exceptions.RayTaskError: ray_ExperimentRunner:train() (pid=4162, host=ricardo-VivoBook-ASUS-Laptop-X505ZA-X505ZA)
  File "/home/ricardo/Documentos/venv_mbpo/env-py3.6/lib/python3.6/site-packages/ray/tune/trainable.py", line 150, in train
    result = self._train()
  File "/home/ricardo/Documentos/mbpo/examples/development/main.py", line 85, in _train
    self._build()
  File "/home/ricardo/Documentos/mbpo/examples/development/main.py", line 46, in _build
    get_environment_from_params(environment_params['training']))
  File "/home/ricardo/Documentos/mbpo/softlearning/environments/utils.py", line 28, in get_environment_from_params
    return get_environment(universe, domain, task, environment_kwargs)
  File "/home/ricardo/Documentos/mbpo/softlearning/environments/utils.py", line 18, in get_environment
    env = ADAPTERS[universe](domain, task, **environment_params)
  File "/home/ricardo/Documentos/mbpo/softlearning/environments/adapters/gym_adapter.py", line 60, in __init__
    self._Serializable__initialize(locals())
AttributeError: 'GymAdapter' object has no attribute '_Serializable__initialize'
```

Is it possible that I am using the wrong version of Serializable?

Thanks.

**Comment by jannerm** [comment]
Yeah, my guess is that this is a serializable version mismatch. Try:
```
python -c "import serializable; print(dir(serializable.Serializable))"
```
The output should be:
```
['_Serializable__initialize', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'clone']
```
which includes the missing attribute as the first item.

You can install the right serializable version (from the [requirements.txt](https://github.com/JannerM/mbpo/blob/master/environment/requirements.txt#L84)) with:

```
pip install git+https://github.com/hartikainen/serializable.git@76516385a3a716ed4a2a9ad877e2d5cbcf18d4e6
```
